### ISSUE TITLE
[EPIC] Prepper Application (Ingest Workflow)

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/heliotrope#1101]
Exploring and investigating the creation of a separate application for the preparation of the SIP. Users would create monographs and associated assets, add metadata, upload files, edit records, and submit them for ingest into Fedora repository. Following a check-in/checkout model, users would check-in their records and update stale records (or deleted records) by checking out the master record located in the Fedora repository.

The following tasks are the first-step in exploring this route:

- [ ] research existing metadata/db mgmt applications for UX examples
- [ ] create mockups and user flows for creating monographs and assets
- [ ] decide on technology stack (vue, react, rails, etc.) 
- [ ] build prototype that creates a monograph

**Comment by sethaj** [comment]
@respinos mentioned Airtable as an example: https://airtable.com/ It looks realy nice.

**Comment by conorom** [comment]
Airtable is amazing, but is this more the reality?
http://ladybird.library.yale.edu/
http://ladybird.library.yale.edu/resources/LadyBird_Power_Point.pdf

I presume this is an old school Library ingest workflow pattern that probably exists in various places in U of M also? Actually mirrors what we have now somewhat (spreadsheets n' folders basically). Which begs the question... does everything have to be web-services based? If you want speed etc (and don't have a huge dev team), then maybe not.

**Comment by respinos** [comment]
Thanks for the link! Our motivation (in DLPS) is that spreadsheets have proven too brittle for long-term data management (which may be different from publishing needs). Too easy to change the schema; too easy to get identifiers wrong, etc.

**Comment by conorom** [comment]
I guess my point is that we already have a bulk ingest that mimics (what I'm guessing is) some sort of (nasty) existing Library practices. We could easily turn that into "bulk edit" with the addition of some sort of "checkout" mechanism (proposed, I believe, by your good self). If time is an issue, and this is part of a grant MVP (everyone loves the TLA "MVP", n'est-ce pas?) we might want to go with this type of thing if it's more realistic. It's not like this is the only remaining major work to do, or that our velocity is zooming-down-the-autobahn speed either. Given that we have a CSV export already, you would think that schema changes can be managed that way. Somehow. Or we could try to focus more on coding it in/for Google Drive/Docs.

I admit that some "fancy pants" web app is the holy grail, but if it's substantially removed from heliotrope then keeping the models/schema identical becomes a challenge there, too, no? Perhaps a worse one.

**Comment by jmcglone** [comment]
Are we abandoning this model for ingesting and updating data in Fulcrum?
