### ISSUE TITLE
Create Fulcrum Edition EPUB spec

### ISSUE THREAD

**Issue by mbakeryo** [mlibrary/heliotrope#1160]
As we develop our EPUB Reader, we will need a specific EPUB specification for creating EPUBs that perform as expected within Cozy Sun Bear.

- [x] Create a GH wiki with a specification for Fulcrum Edition EPUBs

Fulcrum Edition specs might include things such as:
- [ ] marking up chapters/sections
- [ ] improved usage of semantic markup
- [ ] spec for embedded media
- [ ] accessibility specifications (alt text and long descriptions)
- [ ] all the features we've been capturing in [DLXS textclass encoding](https://sites.google.com/a/umich.edu/production-and-technology-intranet/ptg-dpp-documentation/text-class-tagging)

**Comment by jmcglone** [comment]
https://github.com/mlibrary/heliotrope/wiki/Fulcrum-Edition-1.0-Specification

**Comment by jmcglone** [comment]
Blocked until we hire a new developer to focus on Fulcrum EPUB spec and migration from DLXS XML to EPUB

**Comment by jgmorse** [comment]
A document with recommendations is now a deliverable of our agreement with vendor Apex. Tim will be point person on seeing this to completion.

**Comment by jgmorse** [comment]
@jgmorse needs to clean up this ticket to reflect work happening via Apex weekly standup.
