### ISSUE TITLE
Replace unauthorized with options. [EPIC]

### ISSUE THREAD

**Issue by gkostin1966** [mlibrary/heliotrope#1164]
- [x] Examples of options provided in screenshots
- [x] Option 1: login via co-sign
- [x] Option 2: use an IP range from your institution
- [x] Option 3: purchase access

**Comment by jmcglone** [comment]
Refer to HathiTrust and DLXS with screenshots

**Comment by jmcglone** [comment]
Options for Gabii:

![bs_machs_chrome_64 0](https://user-images.githubusercontent.com/1686111/35810566-2396e6e8-0a5a-11e8-88ab-d971369b3f83.jpg)

"Individual access" links to co-sign login where a friend account and password can be entered
"Buy publication" links to the [U-M Press product page](https://www.press.umich.edu/9231782/mid_republican_house_from_gabii)

**Comment by jmcglone** [comment]
Options for HathiTrust:

![screen shot 2018-02-05 at 9 50 45 am](https://user-images.githubusercontent.com/1686111/35810799-dbebb872-0a5a-11e8-86e5-80e7282f7c72.png)

I like the way they do this better, offering multiple options for individuals to login, as well as partner institution drop-down menu, which takes out the guessing for individuals looking to see if their institutions has subscribed to a resource.

**Comment by jgmorse** [comment]
The partner institution drop-down should be its own ticket, so I just created #1564
