### ISSUE TITLE
EPub Module Refactoring

### ISSUE THREAD

**Issue by sethaj** [mlibrary/heliotrope#1172]
The EPub code has moved a little fast. We should take some to to try to refactor it into something a little more managable.

- [x] Subtask EPub Class #1187
- [x] Subtask EPub::Publication.chapters #1205
- [x] Subtask EPub::Chapter.paragraphs #1206
- [x] Subtask Move EPub service from services to lib #1239
- [x] Subtask Move EPub searching from services to lib #1233
- [x] Subtask Move EPub indexing from services to lib #1232
- [x] Subtask better error handling in parts of EPub::Publication #1244
- [x] Move EPubs Search Service to Lib #1284

**Comment by sethaj** [comment]
Remove "safety code" that enforces only "heliotrope" press can have epubs.
