### ISSUE TITLE
Figure out downloads

### ISSUE THREAD

**Issue by mbakeryo** [mlibrary/heliotrope#1308]
Determine how to handle:

- [x] Download of an Epub
- [ ] Download of chapters of an Epub (NOT NEEDED)
- [x] Download of a PDF version if provided
- [ ] Download of a PDF chapter (covered in #1489)

Related to 1270

**Comment by jmcglone** [comment]
The final need is a PDF chapter download, which is covered in #1489
