### ISSUE TITLE
Import a metadata template to a specific monograph from the UI

### ISSUE THREAD

**Issue by mark-dce** [mlibrary/heliotrope#131]
**STORY**
As an editor working on a monograph, I would like to be able to import a metadata/file template from from the monograph view page.

**ACCEPTANCE**
- [ ] There is a button to import a template on the monograph view page (if I have edit rights)
- [ ] After clicking on the import option, I'm prompted for the metadata template to import
- [ ] After closing the template, I'm prompted to select the files that should be imported with the template
- [ ] Once I've chosen a template and files and hit OK, the system uploads the files and begins the import

- [x] #1229 Monograph Reindex Button
- [x] #1235 Monograph Representative Manifest CSV
- [x] #1238 Create Factory For Lib Objects
- [x] #1250 Add streams to Exporter
- [ ] #1306 Add streams to Importer
- [ ] #1165 Storyboard the user flow for ingest
- [ ] #1198 Command-line Monograph CSV metadata update
- [ ] #1262 Add links to concern in exported CSV
- [x] #1311 Add Ingest/Import Actor To Actor Stack
- [ ] #1333 Add Monograph Manifest Button and Wizard
- [ ] #1812 Metadata Download/Upload/Update Cycle

See also #1101 [EPIC] Prepper Application (Ingest Workflow)

**Comment by jmcglone** [comment]
Circle back to this in 3 months.

**Comment by jmcglone** [comment]
@mbakeryo Per our big planning meeting on August 25 2017 and discussion of the dashboard, can this ticket be re-used?

**Comment by mbakeryo** [comment]
@jmcglone Looks like it could!

**Comment by mbakeryo** [comment]
Moved this ticket to spring.
