### ISSUE TITLE
Create Gabii Prototype [EPIC]

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/heliotrope#1371]
To get early user testing and gather feedback from the Gabii team, create a prototype of Gabii Vol. 1 on Fulcrum with sample Gabii 1 content and the latest WebGL build.

Each of these should be turned into individual tickets and linked here:
- [x] #1387 Allow publisher to have a parent publisher
- [x] #1383 Allow child publisher to inherit parent publisher theme
- [x] #1384 Modify breadcrumbs for child publisher's views
- [x] #1393 Create sample Gabii EPUB that includes a figure, a table, multiple sections (Dear Reader, More, Details), and SU links
- [x] #1394 Modify Monograph catalog page to include 3-D model, database, about/help, versioning tabs if the Monograph has rich-media
- [x] #1397 Develop method for reading WebGL assets
- [x] [CSB#115](https://github.com/mlibrary/cozy-sun-bear/issues/115) Event handling for WebGL
- [x] #1441 Add a WebGL widget to CSB
- [x] #1395 Import sample Gabii to staging/preview
- [x] #1396 Build special EPUB/CSB view for Monographs that have a WebGL asset - include widgets: link to database, link to media, 3-D model toggler, WebGL viewer
- [x] #1558 Create JS for EPUB <--> WebGL Communication

**Comment by jmcglone** [comment]
Removed user testing card since it is its own standalone ticket and can be worked on apart from the creation of the prototype.
