### ISSUE TITLE
Generate COUNTER reports for HEB [EPIC]

### ISSUE THREAD

**Issue by jgmorse** [mlibrary/heliotrope#1376]
As an institutional subscriber I want to request a report to be generated and delivered to me in a download. The report delivered to me should reflect only usage from my institution. I need to be able to adjust the timeframe for my generated report.

All reports described below should implement the [COUNTER R5 spec](https://www.projectcounter.org/code-of-practice-five-sections/abstract/).

- [x] Confirm what COUNTER reports we are providing
We should implement all of Master Reports and Standard Reports, metric types, elements, and attributes as specified for the following Host Type Categories:

- eBook
- eBook Collection
- Multimedia

The required reports are:

- [ ] Platform Master Report (PR)
- [ ] Platform Usage Report (PR_P1)
- [ ] Title Master Report (TR)
- [ ] Book Requests (TR_B1)
- [ ] Book Access Denied (TR_B2)
- [ ] Book Usage by Access Type (TR_B3)

Once those reports are implemented:
- [ ] Merge DLXS COUNTER reports to Fulcrum COUNTER reports
- [ ] If we launch with DLXS legacy, continue to aggregate COUNTER reports from DLXS to Fulcrum.

**Comment by jgmorse** [comment]
We need this for the HEB launch in August.

**Comment by jgmorse** [comment]
To ease you in to the spec:
[Friendly Guide for Providers](https://www.projectcounter.org/wp-content/uploads/2017/07/Friendly_Guide_Providers_20170706-1.pdf)
[Technical Notes for Providers](https://www.projectcounter.org/wp-content/uploads/2017/07/Tech_Notes_20170710.pdf)

**Comment by jmcglone** [comment]
From my end of things, I'm curious what UI design needs there will be for this ticket and whether that should be a separate ticket.
