### ISSUE TITLE
[EPIC] ELT Support on Fulcrum

### ISSUE THREAD

**Issue by jgmorse** [mlibrary/heliotrope#1415]
Let's use this issue to collect use cases that emerge during discussions with Kelly Sippell.

- [ ] Set up ELT as a Publisher w/ branding
- [ ] Show previews of restricted videos for unauthorized users
- [ ] "Secondary assets" : hidden from search results, only reachable via links in metadata from some related asset (e.g. the PowerPoint that is featured in a lecture video)

**Comment by mbakeryo** [comment]
As of 2/19/18, still not entirely sure what we'll need to have up on Fulcrum for Fall 2018 (for ALS). Hoping to know more by April 16th meeting. 

Here are the meeting notes: https://docs.google.com/document/d/176Od6HsNPJs7pimpjBz1Sl3rUkMXT6Y6nayftC3YHkU/edit
