### ISSUE TITLE
Add event tracking for EPUB

### ISSUE THREAD

**Issue by mbakeryo** [mlibrary/heliotrope#1427]
As a stakeholder who receives Google Analytics reports or who has access to the GA dashboard, I would like to be able to see readers's interactions with EPUBs recorded in Google Analytics. 

These are the areas that should have event tracking applied:
- [ ] Read link on publisher page
- [ ] Read Book link on monograph page
- [ ] TOC links on monograph page

It would be useful to track clicks in the e-reader to see which tools readers are using, including:
- [ ] Next/Previous navigation arrows
- [ ] Full screen 
- [ ] Get citation (and the citation selected)
- [ ] Search
- [ ] Preferences (and the options within - text size and text display)
- [ ] Navigation slider
- [ ] TOC and links
- [ ] Close button
- [ ] Feedback link
- [ ] Ableplayer controls (embedded in EPUB)
- [ ] Leaflet controls (embedded in EPUB)

**Comment by jmcglone** [comment]
Blocked until CSB can fire events for each feature we want to track
