### ISSUE TITLE
[EPIC] Set up a new press

### ISSUE THREAD

**Issue by mark-dce** [mlibrary/heliotrope#146]
- [x] Configure the subdomain and press title #97
- [x] Set up press users
- [x] Configure theme and brand elements (colors, press landing text, etc.)
- [x] Add a new press subdomain, name, title, and logo #150

**Comment by jmcglone** [comment]
We determined that the items on this list have been completed and that we will create a new ticket with current dashboard needs.
