### ISSUE TITLE
HEB custom metadata fields [EPIC]

### ISSUE THREAD

**Issue by jgmorse** [mlibrary/heliotrope#1475]
- [x] Make list of custom fields on DLXS GUI
- [x] confirm with ACLS which fields are desired
- [ ] Map fields to metadata template
- [ ] Add fields as necessary (eg., copyright holder URL)
- [ ] Add fields to Hyrax data model
- [ ] Update ingest script to use new fields
- [ ] [#1810 Update view page to display new fields](https://github.com/mlibrary/heliotrope/issues/1810)
- [ ] Style new fields
- [ ] Repeat all steps above for assets migrated from DLXS imageclass

Pull in metadata from these sources:
 - [x] DLXS textclass headers
- [ ] HEB mysql database (reviews and related titles)

**Comment by jgmorse** [comment]
Sent spreadsheet to ACLS for review; will follow up 3/16.

https://docs.google.com/spreadsheets/d/1su3zi74ONO30edlf7d60ZrlGTWg9SWZbqG2Srgiyk8g/edit#gid=0

**Comment by mbakeryo** [comment]
@jgmorse Is this still blocked?

**Comment by jmcglone** [comment]
High priority, blocking ingest and QC of HEB.

**Comment by tbelc** [comment]
Below is a link to the spreadsheet for managing the EPUB and Fulcrum metadata:

[https://drive.google.com/open?id=197EY5QSRZ1VjzbmNSSlvqJQr1SZqpokMV4eJ97UCY_A](url)

**Comment by tbelc** [comment]
Status:

1. **Step: Map fields to metadata template**. I believe that this is complete, but it is possible that a field that exists in the MARC record and not in the DLXS header could still be used as a value for a template field.
2. **Step: Add fields as necessary (eg., copyright holder URL)**.  Below is the list of fields that may be added to the Fulcrum metadata template: (1) copyholder name (2) copyholder URL (3) related titles [HEB ID, title, authors, publication info.

**Comment by jgmorse** [comment]
I think we'll also need (4) reviews [journal_abbrev, review_label, review_url] added to the template.
