### ISSUE TITLE
Investigate encoding backlist HEB monographs as fixed layout EPUBS

### ISSUE THREAD

**Issue by jgmorse** [mlibrary/heliotrope#1491]
- [x] Mockup encoding 
- [x] Convert page image files
- [x] embed OCR
- [x] encode multiple renditions
- [ ] index OCR
- [ ] test full text search within CSB
- [ ] embed metadata
- [ ] test in CSB

**Comment by mbakeryo** [comment]
Meeting April 3.
