### ISSUE TITLE
Build new Authentication System (Keycard)

### ISSUE THREAD

**Issue by jgmorse** [mlibrary/heliotrope#1543]
- [ ] A user session includes info on the user's cosign username, if they are logged in.
- [ ] A user session includes an institutional ID for any institution that is associated with the requesting IP address.
- [ ] provide documentation so developers know how to use Authn system
