### ISSUE TITLE
Paywall REST API

### ISSUE THREAD

**Issue by gkostin1966** [mlibrary/heliotrope#1601]
For Heliotrope to be integrated into a publishing ecosystem it needs to provide an external API to allow reads and writes to data within its domain.  As a web application the industry standard is to provide access through a REST API.  The scope of this EPIC is the "Paywall" REST API; everything necessary to support this functionality.

- [x] Paywall REST API Specification #1602
- [x] Paywall REST API Implementation #1604
- [x] Paywall REST API Authorization #1605
- [x] Paywall REST API Authentication #1708
- [ ] Paywall REST API Request Logging #1732

**Comment by gkostin1966** [comment]
Workflow to create licenses for subscribers #1544

**Comment by gkostin1966** [comment]
https://scotch.io/tutorials/build-a-restful-json-api-with-rails-5-part-one
https://scotch.io/tutorials/build-a-restful-json-api-with-rails-5-part-two
https://scotch.io/tutorials/build-a-restful-json-api-with-rails-5-part-three
