### ISSUE TITLE
Document Conceptual Model in Hydra-works terminology

### ISSUE THREAD

**Issue by mark-dce** [mlibrary/heliotrope#206]
**TODO**
 Document the [Conceptual Model](https://drive.google.com/file/d/0B-18ovAEQgwvY0hvN25feWt1ZUk/view?usp=sharing) using the PCDM/Hydra-Works model.  
The document should look something like the diagrams [here](https://github.com/duraspace/pcdm/wiki)

**ACCEPTANCE**
- [ ] Mark gives feedback (June 9, 2016?)
- [x] Jeremy confirms owl:sameAs for clone relationship
- [x] Jeremy updates diagram
- [x] Jeremy posts diagram to demo assets folder
- [ ]  Post on GitHub wiki

**Comment by jgmorse** [comment]
Use owl:sameAs for clone relationship?

**Comment by jgmorse** [comment]
Diagram updated and posted in <a href="https://drive.google.com/drive/u/0/folders/0B-CNui8jTxj4Qi1XNnZWUko2ekU">Stakeholders Resources folder.  Re-posted in #hydra_dce Slack channel for Mark's feedback.

**Comment by jgmorse** [comment]
Updated to v0.2 to incorporate clone relationship.  Link updated in description.  Pinging Mark via email.

**Comment by jmcglone** [comment]
This work has migrated to #726
