### ISSUE TITLE
Deploy to Production

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/heliotrope#347]
To release to production, we must complete the following items:

Pre deployment:
- [x] Modify [db/seeds.rb](https://github.com/mlibrary/heliotrope/blob/5157785b850aebc62b60dd6e2f9ff3f5ce63e0c6/db/seeds.rb) so that only NW press is created
- [x] browser testing in browserstack
- [ ] tag release (what should the tag be?)

Bulleit environment
- [x] ensure that ffmpeg is installed and compiled correctly
- [x] directory permissions match nectar directory permissions
- [x] mod_x_sendfile is enabled
- [x] clamav installed
- [x] make sure we reload solr core per #469

Post deployment:
- [x] #268 - set up domains and redirects
- [x] remove the CNAME file from the [fulcrum gh-pages branch](https://github.com/mlibrary/fulcrum/tree/gh-pages)
- [x] test redirects
- [x] add admin users to production deployment.
- [x] import NW materials
- [x] #44 - ensure non-fulcrum items (DBD) are not discoverable in fulcrum
- [x] QA that derivatives were properly created (esp. thumbnails)
- [x] test that /robots.txt is right for production.
- [x] test that Google Analytics is tracking correctly for NW property
- [x] test that Google Analytics is tracking correctly for MichPub property
- [x]  set up cache_clean in crontab in the same way as on nectar

**Comment by jmcglone** [comment]
Waiting on UMRDR to update to Sufia 7, which uses Fedora 4.5.1

**Comment by sethaj** [comment]
Some browser testing results:
```
Browser testing w/ Browserstack for /northwestern
-------------------------------------------------

	Windows 10
		IE 14
			layout	ok
			leaflet	ok
			video	ok
			autio	ok
		IE 11
			layout	ok
			leaflet	ok
			video	ok
			audio	ok
		FF 48
			layout	ok
			leaflet	ok
			video	ok
			audio	ok
		chrome 53
			layout	ok
			leaflet	ok
			video	ok
			audio	ok
		opera 40
			layout	ok
			leaflet	ok
			video	ok
			audio	ok
		safari 5.1
			layout	ok
			leaflet	ok
			video	ok
			audio	ok
	Windows 7
		IE 10
			layout	ok
			leaflet	ok
			video	ok
			audio	ok
		IE 8 -- NOTHING WORKS
			
	OS X - El Capitan
		safari 9.1
			layout	ok
			leaflet	ok
			video	ok
			audio	ok
		FF 48
			layout	ok
			leaflet	ok
			video	ok
			audio	ok
		chrome 53
			layout	ok
			leaflet	ok
			video	ok
			audio	ok

	OS X - Mavericks
		safari 7.1
			layout 	ok
			leaflet	ok
			video	ok
			audio	Couldn't hear anything in BrowserStack but it looks right?
			
		FF 48
			layout	ok
			leaflet	ok
			video	ok
			audio	Couldn't hear anything in BrowserStack but it looks right?
		chrome 53
			layout	ok
			leaflet	ok
			video	ok
			audio	Couldn't hear anything in BrowserStack but it looks right?

	Linux - Ubuntu 15.10
		chrome 53
			layout 	ok
			leaflet	ok
			video	ok
			audio	ok
		FF 47
			layout 	ok
			leaflet ok
			video	ok
			audio

	Android - Moto X 2nd Gen (not BrowserStack)
			layout 	usable
			leaflet	ok
			video	ok
			audio	ok (but not via BrowserStack, so maybe the other audio problems are really BrowserStack)

	iOS - iPhone 6S - Safari (w/ BrowserStack)
			layout 	usable
			leaflet	ok
			video	sort of... kind of wonky in BrowserStack. We know this works nativly though
			audio	Couldn't hear anything in BrowserStack

	iOS - iPhone 6S - Chrome (w/ BrowserStack)
			layout 	usable
			leaflet	ok
			video	sort of... kind of wonky in BrowserStack. Same as Safari.
			audio	Couldn't hear anything in BrowserStack
```

**Comment by jmcglone** [comment]
Finally found Colin's document re: browser support. The Library does not support IE 8, 9, or 10, so I'm inclined to say it is okay if the site breaks in IE8. See https://github.com/mlibrary/mlibdocs/wiki/Browser-Compatibility-Policy for the full list.
