### ISSUE TITLE
Add Google Analytics tracking

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/heliotrope#348]
Add GA tracking code to the application

- [ ] Northwestern tracking code for NW items
- [ ] FulcrumScholar tracking code for entire application
- [ ] Only on production server
- [ ] Add FulcrumScholar tracking code to `config/initializers/curation_concerns.rb`
- [ ] Add NW tracking code to `db/seeds.rb`

**Comment by jmcglone** [comment]
Look at how UMRDR is doing GA

**Comment by sethaj** [comment]
Here's one way we could do this. Change this line in `config/initializers/curation_concerns.rb` from this:

```
  # config.google_analytics_id = 'UA-99999999-1'
```

to this:

```
  config.google_analytics_id = Settings.google_analytics_id
```

And then in the `heliotrope-deploy` project on nectar in the file `/hydra-dev/heliotrope-deploy/upload/production-config/production.yml` (NOTE: _this deploy target does not yet exist_) add the line:

```
google_analytics_id: THE_ID
```

That's not how umrdr does it, but it should work. It might be better to emulate umrdr, ask Colin.

**Comment by jmcglone** [comment]
This method sounds like it would work, but we'll also need to account for a way to have two tracking IDs. One for MichPub, that will be on all pages. Another that will be for NW, that will only be on NW pages (press catalog, monograph catalog, asset pages).

**Comment by jmcglone** [comment]
@sethaj overall, this looks great. Two things:

1a. I forgot that the DLPS account is using the old google analytics tracking code -- meaning, the JS snippet you have for the fulcrum wide tracking is not correct.

1b. The DLXS collection level tracking code is also a little different and doesn't need to be used.

1c. The tracking code for fulcrum AND a press should be (you'll still want to put the tracking code on the page twice if it is a press' page, with the proper ID dropped in for each):

```
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'GA ID GOES HERE', 'auto');
  ga('send', 'pageview');

</script>
```

2a. So we aren't going to store the fulcrum level GA ID in the `config/initializers/curation_concerns.rb` file? That's fine -- I think I understand the way you're planning to do it with the `secrets.yml` file. 

2b. I think this is clear in the acceptance criteria but to reiterate -- similar to us not wanting to track fulcrum on staging and preview, we don't want to track a press on staging and preview.
