### ISSUE TITLE
Add GA event tracking

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/heliotrope#481]
Add event tracking to press, monograph, and asset pages (on image for zooming purposes, on audio and video playback, on download, on share) for all partners

Fulcrum info pages
- [ ] header and footer links

Press page
- [ ] book titles and book buttons
- [ ] footer links
- [ ] search?

Monograph page
- [ ] asset links
- [ ] buy links
- [ ] browse/sort

Asset page
- [ ] image on zooming tools
- [ ] audio playback buttons
- [ ] video playback buttons
- [ ] downloads
- [ ] share buttons
- [ ] metadata info tabs

**Comment by sethaj** [comment]
From what I can tell, we can have 3 fields to describe what we need for even tracking: 'category', 'action' and 'label'. We also can use 'value', but it has to be a number so I'm not quite sure what to do there.. Here's what I'm thinking as a first try. Would this be useful? I'm not too sure. Should we have titles instead of IDs? Would that be better for a report? I don't know exactly what's best here.

Here's a table. It looks much better on github than it does on the waffleboard.

| category | action | label | value |
| -------- | ------ | ----- | ----- |
| header   | click  | /michigan  |   |
| footer   | click  | /about     |   |
| footer   | click  | http://www.psupress.org/ |   |
| press_page | click | /concern/monographs/zs25x856m |   |
| press_page | search | q=dogs+and+cats |   |
| file_set | click | glk34ims |   |
| monograph_page | click | dxk2ns902 |   |
| monograph_page | click | buy_link |   
| monograph_page | sort | sort=chapter+asc |   |
| file_set | zoom_image | 3mndskjhs |   |
| file_set | play_video | skhss0dn |    |
| file_set | stop_video | dskjhk3s |    |
| file_set | play_audio | v0f8n3sd |    |
| file_set | download | sknkn0cw |    |
| file_set | click_permissions  | pvc0hn2a |   |
| file_set | click_stats | cmnxz02ds |   |

Once we decide what kind of report we actually want, what is actually useful data, we'll need to add the tracking code. This is tricky because:

1) We are sometimes using the press GA id, and sometimes not.
2) Blacklight creates a lot of our links/urls using helpers and it's hard to override them everywhere.
3) The old blacklight-google-analytics plugin just added all tracking via javascript instead of dealing with the templates [ https://github.com/uohull/blacklight_google_analytics/blob/master/app/assets/javascripts/blacklight_google_analytics.js.erb ] . We could go that way, but it looks like we'd need to rely on html elements having an id for jquery to select on, and many times we don't have this. So we'd need to add them. Or add a class or maybe a `data-` attribute describing the kind of tracking we want and to also have something for jquery to select on. We'd need to do this everywhere. This might be the easiest way.

**Comment by mbakeryo** [comment]
@sethaj IMHO, titles would be more useful than IDs on the reports. I like the list of categories/actions you have here. I might add a click_tech (for the technical info tab) and how people decided to view the asset list (list or gallery).

**Comment by jmcglone** [comment]
@sethaj @mbakeryo 

+1 on recording titles instead of IDs

I think your table looks great -- thanks for breaking this down. In addition to MBY's fields, I would also add:

1) search on the monograph catalog page
2) facets on monograph catalog page
3) search on the asset page
4) share button (record what shared service they click on)

I'm not sure on #2 -- but I do think it would be good to know if facets were being used. It may not be important to actually record what facet was applied, but rather what category a facet belonged to (Section, Keyword, Creator, etc.)

**Comment by sethaj** [comment]
I'm going to make a google doc for the event tracking table. I think it makes sense to work this all out before we start tracking anything. I'll share it along with some of my questions with the group.
