### ISSUE TITLE
Additional meta tags for the monograph catalog page

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/heliotrope#683]
The monograph page should display additional metatags to assist with future Altmetric implementation:

- [ ] meta_publisher, ie `<meta name="citation_publisher" content="University of Michigan Press">`
- [ ] meta_isbn, ie `<meta name="citation_isbn" content="123-456-78901">`
- [ ] these tags should not appear on the asset page.
