### ISSUE TITLE
Validate an EPUB3 file

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/heliotrope#721]
- [ ] When I upload/ingest an EPUB3 asset the system reads runs the file through checks to validate that the asset is indeed a valid EPUB3 package.
- [ ] When it is not a valid EPUB3 asset, a message is displayed on the asset upload page (or terminal?) to the user indicating it is an invalid EPUB3 file.
- [ ] When it is a valid EPUB3 asset, a message is displayed on the asset upload page (or terminal?) to the user indicating it is a valid EPUB3 file.

**Comment by jmcglone** [comment]
There may be pre-existing libraries created by IDPF that we can use to run basic validation checks on an EPUB3 file.

In the future, we will want to modify those specs according to those set out by Library digital preservation.

**Comment by mbakeryo** [comment]
Refer to #1160

**Comment by jgmorse** [comment]
We should base our validator on whatever HathiTrust is using for Epub validation.  Talk to aelkiss.

**Comment by jmcglone** [comment]
See also #1160
