### ISSUE TITLE
A subscriber can access a restricted resource

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/heliotrope#728]
If an authenticated user attempts to access a restricted resource, the app should check an authz database to see if the user should access the resource.

- [x] #1543: App has info on the user: either a cosign username, or their institution.
- [x] App can refer to a policy that states whether the user has privileges to the restricted resource.
- [x] If the user has privileges, they get access.
- [x] #1164:  If the user does not have access, they don't get access and get a message explaining so.
- [x] #1164 : If the app doesn't know who the user is, it presents options for logging in, or instructs them to speak to their library. 

BLOCKED by #1543
