### ISSUE TITLE
[EPIC] Dashboard

### ISSUE THREAD

**Issue by gkostin1966** [mlibrary/heliotrope#739]
**EPIC**
As a registered user I'd like a place to go to find information relevant to me.
See http://mlibrary.github.io/elderberry/admin/index.html# for a potential layout for the page.

**STORIES**
- [x] #201 Dashboard 
- [ ] #740 Dashboard Registered User
- [ ] #737 Dashboard Users Index Page
- [ ] #738 Dashboard User Show Page
- [ ] #735  Dashboard Presses Index Page
- [ ] #727  Dashboard Press Show Page

**Comment by mbakeryo** [comment]
Dashboard user story/planning meeting set for March 22, 2017. Agenda is here: https://docs.google.com/document/d/16_bW1SrpedD7MVntDy6xc2C1Zg3hIycT6rJndAHg6Ik/edit

**Comment by mbakeryo** [comment]
Per our meeting of 3/22/17, need to write up user stories for our next bit of dashboard development (with the focus on Platform Admin).

**Comment by jmcglone** [comment]
@gkostin1966 flagging this one as in need of clean-up  - I think some of the sub-tasks in this ticket overlap with more recently created tickets.

**Comment by gkostin1966** [comment]
Moving this to the done column since the dashboard exist as a skeleton framework.
