### ISSUE TITLE
EPUB Reader App Spike

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/heliotrope#783]
#Create a basic EPUB reader wrapper application

- [x] setup a separate GitHub repo for this codebase (cozy-sun-bear)
- [x] roughly sketch out the architecture (Seth, Roger, Jon, Greg)
- [x] [cozy-sun-bear#1](https://github.com/mlibrary/cozy-sun-bear/issues/1)
- [x] [cozy-sun-bear#2](https://github.com/mlibrary/cozy-sun-bear/issues/2)
- [x] [cozy-sun-bear#3](https://github.com/mlibrary/cozy-sun-bear/issues/3)
- [x] [cozy-sun-bear#4](https://github.com/mlibrary/cozy-sun-bear/issues/4)

**Comment by jmcglone** [comment]
All sub-tickets and acceptance criteria for this ticket have been completed, so I'm closing this ticket.
